# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Subject name (e.g., 'Mathematics', 'Physics')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Subject overview and learning objectives')),
                ('icon', models.CharField(blank=True, help_text="Icon class for UI (e.g., 'fas fa-calculator')", max_length=50)),
                ('color_code', models.CharField(default='#3498db', help_text='Hex color for visual identification', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether subject is currently offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Resource title', max_length=300)),
                ('description', models.TextField(help_text='What this resource covers')),
                ('resource_type', models.CharField(choices=[('video', 'Video Tutorial'), ('article', 'Article/Blog'), ('pdf', 'PDF Document'), ('quiz', 'Practice Quiz'), ('project', 'Hands-on Project'), ('interactive', 'Interactive Demo')], help_text='Content format - matches learning styles', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Resource difficulty for adaptive recommendations', max_length=10)),
                ('url', models.URLField(blank=True, help_text='External link (YouTube, article, etc.)')),
                ('file', models.FileField(blank=True, help_text='Uploaded file (PDF, etc.)', null=True, upload_to='resources/')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Estimated time to complete (for videos/articles)', null=True)),
                ('author', models.CharField(blank=True, help_text='Content creator', max_length=200)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times accessed')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='User ratings (0-5 stars)', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('is_verified', models.BooleanField(default=False, help_text='Admin-approved quality content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who added this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_resources',
                'ordering': ['-average_rating', '-view_count'],
            },
        ),
        migrations.CreateModel(
            name='LearningActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', help_text='Current activity state', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When student began this resource')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When student finished (null if incomplete)', null=True)),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent on this resource')),
                ('progress_percentage', models.IntegerField(default=0, help_text='How much of the resource was consumed', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('revisit_count', models.IntegerField(default=0, help_text='Number of times student returned to this resource')),
                ('rating', models.IntegerField(blank=True, help_text="Student's rating of this resource", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, help_text="Student's comments about the resource")),
                ('was_helpful', models.BooleanField(blank=True, help_text='Did this resource help the student? (for recommendations)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student performing the activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.studentprofile')),
                ('resource', models.ForeignKey(help_text='Resource being studied', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='learning.learningresource')),
            ],
            options={
                'verbose_name_plural': 'Learning Activities',
                'db_table': 'learning_activities',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Topic name (e.g., 'Linear Equations')", max_length=200)),
                ('description', models.TextField(help_text='What students will learn in this topic')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Base difficulty - used for adaptive learning', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1.0, help_text='Expected time to master this topic', max_digits=5)),
                ('order', models.IntegerField(default=0, help_text='Display order within subject')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Topics that should be learned first', related_name='dependent_topics', to='learning.topic')),
                ('subject', models.ForeignKey(help_text='Parent subject', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subject')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['subject', 'order', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score achieved (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='Maximum possible score', max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Calculated percentage', max_digits=5)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('test', 'Test'), ('assignment', 'Assignment'), ('project', 'Project'), ('exam', 'Exam')], help_text='Type of assessment', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Assessment difficulty', max_length=20)),
                ('time_taken_minutes', models.IntegerField(help_text='Time spent on assessment')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, help_text='When assessment was completed')),
                ('strengths', models.JSONField(default=list, help_text='Subtopics where student excelled')),
                ('weaknesses', models.JSONField(default=list, help_text='Subtopics needing improvement')),
                ('teacher_feedback', models.TextField(blank=True, help_text="Teacher's comments")),
                ('student', models.ForeignKey(help_text='Student being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='accounts.studentprofile')),
                ('topic', models.ForeignKey(help_text='Topic being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='learning.topic')),
            ],
            options={
                'verbose_name_plural': 'Student Performances',
                'db_table': 'student_performances',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddField(
            model_name='learningresource',
            name='topic',
            field=models.ForeignKey(help_text='Associated topic', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.topic'),
        ),
    ]
