# Generated by Django 6.0.1 on 2026-01-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(default='all', help_text="Grade level (e.g., '9th', '10th', '11th', 'all')", max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade_level',
            field=models.CharField(default='all', help_text="Grade level (e.g., '9th', '10th', '11th', 'all')", max_length=50),
        ),
    ]
