# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Path name (e.g., 'Master Algebra')", max_length=200)),
                ('description', models.TextField(help_text='What this path will achieve')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', help_text='Current path status', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Overall completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_step', models.IntegerField(default=1, help_text='Which step student is currently on')),
                ('estimated_completion_days', models.IntegerField(help_text='Expected days to complete path')),
                ('started_at', models.DateTimeField(blank=True, help_text='When student began this path', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When student finished path', null=True)),
                ('is_ai_generated', models.BooleanField(default=True, help_text='Was this path auto-generated by AI?')),
                ('generation_criteria', models.JSONField(default=dict, help_text='Factors used to create this path (for transparency)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student following this path', on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'learning_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Order in the learning path')),
                ('title', models.CharField(help_text='Step title', max_length=200)),
                ('description', models.TextField(help_text='What to achieve in this step')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', help_text='Current step status', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Step completion percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Expected time to complete step', max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_path', models.ForeignKey(help_text='Parent learning path', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recommendations.learningpath')),
                ('recommended_resources', models.ManyToManyField(blank=True, help_text='Resources to complete this step', related_name='path_steps', to='learning.learningresource')),
                ('topic', models.ForeignKey(help_text='Topic for this step', on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
            ],
            options={
                'db_table': 'learning_path_steps',
                'ordering': ['learning_path', 'step_number'],
                'unique_together': {('learning_path', 'step_number')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='topics',
            field=models.ManyToManyField(help_text='Topics in this learning path', related_name='learning_paths', through='recommendations.LearningPathStep', to='learning.topic'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('resource', 'Learning Resource'), ('topic', 'Topic to Study'), ('revision', 'Revision Reminder'), ('practice', 'Practice Exercise'), ('project', 'Hands-on Project')], help_text='Type of recommendation', max_length=20)),
                ('title', models.CharField(help_text='Recommendation title', max_length=300)),
                ('description', models.TextField(help_text='What student should do')),
                ('reason', models.TextField(help_text='WHY this recommendation was made (transparency)')),
                ('reasoning_factors', models.JSONField(default=dict, help_text="Data points used in recommendation logic (e.g., {'low_score': 45, 'topic': 'Algebra'})")),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', help_text='Urgency level', max_length=10)),
                ('recommended_date', models.DateField(help_text='When to show this recommendation')),
                ('expires_at', models.DateField(blank=True, help_text='When recommendation becomes irrelevant', null=True)),
                ('is_viewed', models.BooleanField(default=False, help_text='Has student seen this?')),
                ('is_acted_upon', models.BooleanField(default=False, help_text='Did student follow the recommendation?')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When student viewed recommendation', null=True)),
                ('acted_at', models.DateTimeField(blank=True, help_text='When student took action', null=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Student feedback - improves future recommendations', null=True)),
                ('student_feedback', models.TextField(blank=True, help_text="Student's comments on recommendation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(blank=True, help_text="Recommended resource (if type is 'resource')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.learningresource')),
                ('student', models.ForeignKey(help_text='Student receiving recommendation', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.studentprofile')),
                ('topic', models.ForeignKey(blank=True, help_text="Recommended topic (if type is 'topic')", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='learning.topic')),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-priority', '-recommended_date'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('recommendation', 'Recommendation Feedback'), ('resource', 'Resource Feedback'), ('system', 'System Feedback'), ('teacher', 'Teacher Feedback')], help_text='Type of feedback', max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Numerical rating')),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback')),
                ('was_helpful', models.BooleanField(help_text='Did this help your learning?')),
                ('was_accurate', models.BooleanField(blank=True, help_text='Was the recommendation accurate to your needs?', null=True)),
                ('difficulty_appropriate', models.BooleanField(blank=True, help_text='Was the difficulty level appropriate?', null=True)),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has admin/teacher reviewed this feedback?')),
                ('admin_response', models.TextField(blank=True, help_text='Response from admin/teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(blank=True, help_text='Related resource (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='learning.learningresource')),
                ('student', models.ForeignKey(blank=True, help_text='Student providing feedback', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.studentprofile')),
                ('recommendation', models.ForeignKey(blank=True, help_text='Related recommendation (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendation')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
