# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Assessment title', max_length=300)),
                ('description', models.TextField(help_text='Assessment overview and instructions')),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quick Quiz'), ('test', 'Test'), ('assignment', 'Assignment'), ('practice', 'Practice Set'), ('exam', 'Exam')], help_text='Type of assessment', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('mixed', 'Mixed Difficulty')], default='medium', help_text='Overall difficulty level', max_length=10)),
                ('total_marks', models.IntegerField(help_text='Maximum possible score')),
                ('passing_marks', models.IntegerField(help_text='Minimum score to pass')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Time limit (null = no limit)', null=True)),
                ('is_adaptive', models.BooleanField(default=False, help_text='Does difficulty adjust based on performance?')),
                ('is_ai_generated', models.BooleanField(default=False, help_text='Was this assessment auto-generated?')),
                ('bloom_distribution', models.JSONField(default=dict, help_text="Question distribution by Bloom's levels (e.g., {'remember': 30, 'understand': 40, 'apply': 30})")),
                ('is_published', models.BooleanField(default=False, help_text='Is assessment available to students?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Teacher who created this assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='accounts.teacherprofile')),
                ('topic', models.ForeignKey(help_text='Topic being assessed', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='learning.topic')),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question being asked')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('essay', 'Essay'), ('fill_blank', 'Fill in the Blank')], help_text='Question format', max_length=20)),
                ('options', models.JSONField(default=list, help_text="Answer options for MCQ (e.g., ['Option A', 'Option B', 'Option C', 'Option D'])")),
                ('correct_answer', models.TextField(help_text='Correct answer (option index for MCQ, text for others)')),
                ('marks', models.IntegerField(default=1, help_text='Points for this question')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Question difficulty', max_length=10)),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='understand', help_text="Bloom's taxonomy level", max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Explanation of correct answer (shown after submission)')),
                ('times_attempted', models.IntegerField(default=0, help_text='How many times this question was answered')),
                ('times_correct', models.IntegerField(default=0, help_text='How many times answered correctly')),
                ('order', models.IntegerField(default=0, help_text='Question order in assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(help_text='Parent assessment', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('evaluated', 'Evaluated')], default='in_progress', help_text='Current attempt status', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score achieved', max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage score', max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When attempt began')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When attempt was submitted', null=True)),
                ('time_taken_minutes', models.IntegerField(default=0, help_text='Total time spent')),
                ('correct_answers', models.IntegerField(default=0, help_text='Number of correct answers')),
                ('wrong_answers', models.IntegerField(default=0, help_text='Number of wrong answers')),
                ('skipped_questions', models.IntegerField(default=0, help_text='Number of unanswered questions')),
                ('mistakes', models.JSONField(default=list, help_text='List of question IDs answered incorrectly')),
                ('weak_topics', models.JSONField(default=list, help_text='Topics where student struggled')),
                ('teacher_feedback', models.TextField(blank=True, help_text="Teacher's comments on attempt")),
                ('suspicious_activity', models.BooleanField(default=False, help_text='Flag for unusual patterns (e.g., too fast, random guessing)')),
                ('activity_log', models.JSONField(default=list, help_text='Timestamps of actions for pattern analysis')),
                ('assessment', models.ForeignKey(help_text='Assessment being attempted', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('student', models.ForeignKey(help_text='Student taking the assessment', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField(blank=True, help_text="Student's submitted answer")),
                ('is_correct', models.BooleanField(default=False, help_text='Whether answer was correct')),
                ('marks_awarded', models.DecimalField(decimal_places=2, default=0, help_text='Marks given for this answer', max_digits=5)),
                ('time_taken_seconds', models.IntegerField(default=0, help_text='Time spent on this question')),
                ('answered_at', models.DateTimeField(auto_now_add=True, help_text='When answer was submitted')),
                ('confidence_level', models.IntegerField(blank=True, help_text="Student's confidence in their answer (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question', models.ForeignKey(help_text='Question being answered', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.question')),
                ('attempt', models.ForeignKey(help_text='Parent quiz attempt', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.quizattempt')),
            ],
            options={
                'db_table': 'question_responses',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
