# Generated by Django 6.0.1 on 2026-01-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Deadline for assignment submission (optional)', null=True),
        ),
    ]
