# Generated by Django 5.1.5 on 2026-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('quiz', 'Quick Quiz'), ('test', 'Test'), ('assignment', 'Assignment'), ('practice', 'Practice Set'), ('exam', 'Exam'), ('diagnostic', 'Diagnostic Assessment')], help_text='Type of assessment', max_length=20),
        ),
    ]
