# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_id', models.CharField(help_text="Unique identifier (e.g., 'first_quiz', '7_day_streak')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Badge name (e.g., 'Quiz Master')", max_length=100)),
                ('description', models.TextField(help_text='How to earn this badge')),
                ('category', models.CharField(choices=[('streak', 'Streak Achievement'), ('quiz', 'Quiz Achievement'), ('topic', 'Topic Mastery'), ('level', 'Level Achievement'), ('special', 'Special Achievement')], help_text='Badge category', max_length=20)),
                ('icon', models.CharField(help_text='Icon class or emoji', max_length=50)),
                ('xp_reward', models.IntegerField(default=0, help_text='Bonus XP for earning this badge')),
                ('is_rare', models.BooleanField(default=False, help_text='Is this a rare/special badge?')),
                ('times_awarded', models.IntegerField(default=0, help_text='How many students have earned this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'badges',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0, help_text='Total experience points earned', validators=[django.core.validators.MinValueValidator(0)])),
                ('current_level', models.IntegerField(default=1, help_text='Current level (calculated from XP)', validators=[django.core.validators.MinValueValidator(1)])),
                ('xp_to_next_level', models.IntegerField(default=100, help_text='XP needed to reach next level')),
                ('current_streak', models.IntegerField(default=0, help_text='Consecutive days of activity')),
                ('longest_streak', models.IntegerField(default=0, help_text='Best streak ever achieved')),
                ('last_activity_date', models.DateField(blank=True, help_text='Last day student was active', null=True)),
                ('badges_earned', models.JSONField(default=list, help_text="List of badge IDs earned (e.g., ['first_quiz', 'week_streak', 'topic_master'])")),
                ('total_badges', models.IntegerField(default=0, help_text='Count of unique badges')),
                ('total_quizzes_completed', models.IntegerField(default=0, help_text='Number of quizzes finished')),
                ('total_resources_viewed', models.IntegerField(default=0, help_text='Number of learning resources accessed')),
                ('total_topics_mastered', models.IntegerField(default=0, help_text='Topics with >80% proficiency')),
                ('rank_in_class', models.IntegerField(blank=True, help_text='Position in class leaderboard', null=True)),
                ('rank_globally', models.IntegerField(blank=True, help_text='Position in global leaderboard', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text="Student's gamification profile", on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='accounts.studentprofile')),
            ],
            options={
                'db_table': 'gamification_profiles',
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('one_on_one', 'One-on-One Session'), ('remedial', 'Remedial Class'), ('resource', 'Additional Resources'), ('parent_contact', 'Parent Contact'), ('peer_tutoring', 'Peer Tutoring'), ('other', 'Other')], help_text='Type of intervention', max_length=20)),
                ('reason', models.TextField(help_text="Why intervention was needed (e.g., 'Low quiz scores in Algebra')")),
                ('description', models.TextField(help_text='What was done during intervention')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Current status', max_length=20)),
                ('scheduled_date', models.DateField(help_text='When intervention is/was scheduled')),
                ('completed_date', models.DateField(blank=True, help_text='When intervention was completed', null=True)),
                ('outcome', models.TextField(blank=True, help_text='Results of intervention')),
                ('was_effective', models.BooleanField(blank=True, help_text='Did intervention help? (measured by subsequent performance)', null=True)),
                ('follow_up_needed', models.BooleanField(default=False, help_text='Does student need additional support?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student receiving help', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(help_text='Teacher providing intervention', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='accounts.teacherprofile')),
            ],
            options={
                'db_table': 'teacher_interventions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('create', 'Create Record'), ('update', 'Update Record'), ('delete', 'Delete Record'), ('view', 'View Record'), ('download', 'Download File'), ('submit', 'Submit Assessment'), ('grade', 'Grade Assessment'), ('recommend', 'Generate Recommendation')], help_text='Action performed', max_length=20)),
                ('model_name', models.CharField(blank=True, help_text="Django model affected (e.g., 'StudentProfile')", max_length=100)),
                ('object_id', models.IntegerField(blank=True, help_text='ID of affected record', null=True)),
                ('description', models.TextField(help_text='Human-readable description of action')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/device information', max_length=300)),
                ('changes', models.JSONField(default=dict, help_text='Before/after values for updates')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action occurred')),
                ('user', models.ForeignKey(help_text='User who performed action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
