# Generated by Django 5.1.5 on 2026-01-24 00:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0001_initial'),
        ('learning', '0002_subject_grade_level_topic_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks scored by student', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks possible', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Calculated percentage (auto-computed)', max_digits=5)),
                ('assessment_title', models.CharField(blank=True, help_text="Optional title (e.g., 'Unit Test 1', 'Class Quiz')", max_length=200)),
                ('assessment_date', models.DateField(help_text='Date when assessment was conducted')),
                ('notes', models.TextField(blank=True, help_text="Teacher's comments/feedback for student")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student receiving the mark', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_marks', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(help_text='Teacher who entered the mark', on_delete=django.db.models.deletion.CASCADE, related_name='marks_given', to='accounts.teacherprofile')),
                ('topic', models.ForeignKey(help_text='Topic/subject for this assessment', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_marks', to='learning.topic')),
            ],
            options={
                'db_table': 'teacher_marks',
                'ordering': ['-assessment_date', '-created_at'],
                'indexes': [models.Index(fields=['student', '-assessment_date'], name='teacher_mar_student_6ceb2c_idx'), models.Index(fields=['teacher', '-assessment_date'], name='teacher_mar_teacher_7c48af_idx')],
            },
        ),
    ]
