# Generated by Django 6.0.1 on 2026-01-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0002_teachermark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text="e.g., 'Term 1', 'Mid-Term', 'Final Exam'", max_length=50)),
                ('academic_session', models.CharField(help_text="e.g., '2025-26'", max_length=20)),
                ('grades_data', models.JSONField(default=dict, help_text='Subject-wise marks and grades')),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall performance percentage', max_digits=5)),
                ('remarks', models.TextField(help_text="Teacher's overall evaluation and behavioral notes")),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Student's attendance for the term", max_digits=5, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Is the report card visible to student and parent?')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student receiving this report card', on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='accounts.studentprofile')),
                ('teacher', models.ForeignKey(help_text='Teacher issuing the report card', on_delete=django.db.models.deletion.CASCADE, related_name='issued_report_cards', to='accounts.teacherprofile')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-issued_date'],
                'unique_together': {('student', 'term', 'academic_session')},
            },
        ),
    ]
