# Generated by Django 6.0.1 on 2026-01-23 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin')], help_text="User's primary role in the system", max_length=10)),
                ('phone', models.CharField(blank=True, help_text='Contact number for notifications', max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='User avatar for personalization', null=True, upload_to='profiles/')),
                ('is_verified', models.BooleanField(default=False, help_text='Email/phone verification status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text="Receive email updates about child's progress")),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS alerts for critical issues')),
                ('notification_frequency', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Report'), ('critical', 'Critical Alerts Only')], default='weekly', help_text='How often to receive progress updates', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(help_text="Current grade/class (e.g., '10th Grade', 'College Year 1')", max_length=20)),
                ('school_name', models.CharField(blank=True, help_text='Educational institution name', max_length=200)),
                ('learning_style', models.CharField(choices=[('visual', 'Visual Learner'), ('reading', 'Reading/Writing Learner'), ('practice', 'Practice-Heavy Learner'), ('mixed', 'Mixed Learning Style')], default='mixed', help_text='Preferred learning method - drives content recommendations', max_length=20)),
                ('learning_pace', models.CharField(choices=[('fast', 'Fast Learner'), ('average', 'Average Pace'), ('slow', 'Needs More Time')], default='average', help_text='Learning speed - affects difficulty progression', max_length=20)),
                ('target_subjects', models.JSONField(default=list, help_text='List of subjects student wants to focus on')),
                ('academic_goals', models.TextField(blank=True, help_text="Student's learning objectives and aspirations")),
                ('total_study_time', models.IntegerField(default=0, help_text='Total minutes spent learning (for analytics)')),
                ('current_streak', models.IntegerField(default=0, help_text='Consecutive days of activity (gamification)')),
                ('longest_streak', models.IntegerField(default=0, help_text='Best streak achieved (motivation)')),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last platform interaction (for dropout detection)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Connected parent account for monitoring', limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.JSONField(default=list, help_text='List of subjects/topics teacher specializes in')),
                ('qualification', models.CharField(help_text="Educational qualifications (e.g., 'M.Ed in Mathematics')", max_length=200)),
                ('experience_years', models.IntegerField(default=0, help_text='Years of teaching experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('school_name', models.CharField(blank=True, help_text='Current institution', max_length=200)),
                ('teaching_style', models.TextField(blank=True, help_text='Description of teaching methodology')),
                ('total_students', models.IntegerField(default=0, help_text='Number of students taught on platform')),
                ('total_assessments_created', models.IntegerField(default=0, help_text='Assessments created (for contribution tracking)')),
                ('is_verified_teacher', models.BooleanField(default=False, help_text='Admin verification status for quality control')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to user account', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
    ]
