# Generated by Django 5.1.5 on 2026-01-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='has_taken_diagnostic',
            field=models.BooleanField(default=False, help_text='Whether student has completed the initial diagnostic assessment'),
        ),
    ]
